require('./bootstrap');
require('./global/alert-message')
require('./global/notification')
require('./global/menu')
// require('./global/sign_in')
require('./global/short-text.js')
require('./global/chat.js')
// require('./global/slider')
require('./global/questionnaire')
require('./global/search')
require('./main')
